export const html = `<section class="viewer-card owner-tools"><details id="canary-panel"><summary>Canary</summary><p class="form-help">CanaryのURLへのアクセスを記録します。PDFの閲覧通知とは別の記録です。</p><p id="canary-status" role="status" aria-live="polite"></p><div id="canary-controls" hidden><div class="actions"><button id="canary-create" type="button" class="primary" disabled>Canaryを設定</button><button id="canary-revoke" type="button" disabled>Canaryを停止</button><button id="canary-refresh" type="button" class="quiet">再読み込み</button></div><label for="canary-url">Canary URL</label><textarea id="canary-url" rows="2" readonly spellcheck="false"></textarea><button id="canary-copy" type="button" disabled>URLをコピー</button><p id="canary-deadline" class="form-help"></p><button id="canary-logs" type="button" class="quiet">Canaryの記録を確認</button><ul id="canary-events" class="owner-list"></ul></div><details class="management-notes"><summary>ご案内</summary><p>URLが読み込まれると通知対象になります。PDFを開いたことを証明するものではありません。接続元IP・ネットワーク・参照元サイトは、閲覧者本人や所属先を確認するものではありません。</p></details></details></section>`;

export const js = `"use strict";
const names=["canary-panel","canary-status","canary-controls","canary-create","canary-revoke","canary-refresh","canary-url","canary-copy","canary-deadline","canary-logs","canary-events"];
const el=Object.fromEntries(names.map(name=>[name,document.getElementById(name)]));
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/,TOKEN=/^kr_[a-f0-9]{64}$/;
let id=null,data=null,busy=false,uncertain=false,epoch=0,visible=true,expiryTimer=null;
const controllers=new Set();
function active(g){return visible&&g===epoch;}
function dateLabel(value){return new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).format(value);}
function on(){return Boolean(data?.configured&&data.canary?.state==="active"&&data.canary.expiresAt>Date.now());}
function render(){clearTimeout(expiryTimer);const enabled=Boolean(data?.configured),active=on();el["canary-controls"].hidden=!enabled;el["canary-create"].disabled=busy||uncertain||!enabled||active;el["canary-revoke"].disabled=busy||uncertain||!active;el["canary-copy"].disabled=busy||uncertain||!active;el["canary-refresh"].disabled=busy;el["canary-logs"].disabled=busy||!enabled;el["canary-url"].value=active?data.canary.url:"";el["canary-deadline"].textContent=data?.canary?"Canaryの期限："+dateLabel(data.canary.expiresAt)+"（日本時間）":"";if(active)expiryTimer=setTimeout(render,Math.min(2147483647,Math.max(1,data.canary.expiresAt-Date.now())));}
async function api(path,body){const c=new AbortController();controllers.add(c);const timer=setTimeout(()=>c.abort(),15000);try{const r=await fetch(path,{method:body===undefined?"GET":"POST",credentials:"same-origin",cache:"no-store",redirect:"error",signal:c.signal,...(body===undefined?{}:{headers:{"content-type":"application/json"},body:JSON.stringify(body)})});if(!r.ok){const e=new Error();e.status=r.status;throw e;}if(!r.headers.get("content-type")?.startsWith("application/json")||Number(r.headers.get("content-length"))>65536)throw new Error();const reader=r.body.getReader(),parts=[];let size=0;try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>65536)throw new Error();parts.push(value);}}finally{void reader.cancel().catch(()=>{});reader.releaseLock();}const bytes=new Uint8Array(size);let at=0;for(const part of parts){bytes.set(part,at);at+=part.length;}return JSON.parse(new TextDecoder("utf-8",{fatal:true}).decode(bytes));}finally{clearTimeout(timer);controllers.delete(c);}}
function checked(value){if(!value||typeof value.configured!=="boolean"||value.documentId!==id||!(value.canary===null||value.configured&&value.canary&&TOKEN.test(value.canary.token)&&["active","expired","revoked"].includes(value.canary.state)&&Number.isSafeInteger(value.canary.expiresAt)&&value.canary.expiresAt>0&&value.canary.expiresAt<=8640000000000000&&Number.isSafeInteger(value.canary.hitCount)&&value.canary.hitCount>=0&&value.canary.url==="https://kanariya.toppymicros.com/canary/"+value.canary.token))throw new Error();return value;}
function exact(value,fields){return value&&typeof value==="object"&&!Array.isArray(value)&&Object.keys(value).length===fields.length&&fields.every(field=>Object.hasOwn(value,field));}
function validIP(value){if(typeof value!=="string"||!value||value.length>45||/[\\x00-\\x20\\x7f-\\x9f]/.test(value))return false;if(value.includes(":")){if(value.includes("%")||value.includes("[")||value.includes("]"))return false;try{return new URL("http://["+value+"]/").hostname.startsWith("[");}catch{return false;}}const parts=value.split(".");return parts.length===4&&parts.every(part=>/^(?:0|[1-9][0-9]{0,2})$/.test(part)&&Number(part)<=255);}
function validHost(value){if(typeof value!=="string"||value.length>253||/[\\x00-\\x20\\x7f-\\x9f]/.test(value))return false;if(!value)return true;try{const url=new URL("https://"+value+"/");return url.hostname===value&&url.host===value&&!url.username&&!url.password&&url.pathname==="/"&&!url.search&&!url.hash;}catch{return false;}}
function checkedSource(value){if(value===null)return null;if(!exact(value,["ip","country","asn","network","refererHost"])||!validIP(value.ip)||typeof value.country!=="string"||!/^(?:[A-Z]{2})?$/.test(value.country)||!(value.asn===null||Number.isSafeInteger(value.asn)&&value.asn>0&&value.asn<=4294967295)||typeof value.network!=="string"||value.network.length>160||/[\\x00-\\x1f\\x7f-\\x9f]/.test(value.network)||!validHost(value.refererHost))throw new Error();return value;}
function checkedEvent(event){if(!(exact(event,["id","at","outcome","notifications"])||exact(event,["id","at","outcome","notifications","source"]))||!/^[a-f0-9]{32}$/.test(event.id)||!Number.isSafeInteger(event.at)||event.at<=0||event.at>8640000000000000||event.outcome!=="url_requested"||!Array.isArray(event.notifications)||event.notifications.length>4||event.notifications.some(n=>!exact(n,["type","state"])||!["email","webhook","slack","discord"].includes(n.type)||!["accepted","pending","retrying","failed"].includes(n.state)))throw new Error();return {...event,source:Object.hasOwn(event,"source")?checkedSource(event.source):null};}
function sourceLabel(source){if(!source)return "接続元情報なし";const parts=["接続元IP: "+source.ip+(source.country?"（"+source.country+"）":"")];if(source.network||source.asn!==null)parts.push("ネットワーク: "+source.network+(source.asn!==null?(source.network?" ":"")+"AS"+source.asn:""));if(source.refererHost)parts.push("参照元サイト: "+source.refererHost);return parts.join(" ／ ");}
async function read(){if(busy||!id)return;busy=true;render();const g=epoch;try{const value=checked(await api("/v1/documents/"+id+"/canary"));if(!active(g))return;data=value;uncertain=false;el["canary-status"].textContent=!value.configured?"Canaryは未接続です。接続設定が必要です。":on()?"Canaryは有効です。":value.canary?"Canaryは停止しています。":"Canaryは未設定です。";}catch(e){if(active(g)){data=null;el["canary-status"].textContent=e.status===401||e.status===403?"管理者としてログインし直してください。":"状態を確認できません。管理ページを開き直してください。";}}finally{if(active(g)){busy=false;render();}}}
async function change(action){if(busy||uncertain||!data?.configured||action==="create"&&on()||action==="revoke"&&!on())return;busy=true;render();const g=epoch;try{const result=checked(await api("/v1/documents/"+id+"/canary",{action}));if(!active(g))return;data=result;el["canary-status"].textContent=action==="create"?"Canaryを設定しました。":"Canaryを停止しました。";}catch(e){if(active(g)){uncertain=true;el["canary-status"].textContent=e.status===409?"設定が変更されています。再読み込みして確認してください。":"変更結果を確認できません。再読み込みして確認してください。";}}finally{if(active(g)){busy=false;render();}}}
el["canary-create"].addEventListener("click",()=>void change("create"));el["canary-revoke"].addEventListener("click",()=>void change("revoke"));el["canary-refresh"].addEventListener("click",()=>void read());
el["canary-copy"].addEventListener("click",async()=>{render();if(el["canary-copy"].disabled)return;try{await navigator.clipboard.writeText(el["canary-url"].value);el["canary-status"].textContent="Canary URLをコピーしました。";}catch{el["canary-status"].textContent="Canary URLを選択してコピーしてください。";}});
el["canary-logs"].addEventListener("click",async()=>{if(busy||!data?.configured||!id)return;busy=true;render();const g=epoch;try{const result=await api("/v1/documents/"+id+"/canary-logs");if(!active(g))return;if(!exact(result,["configured","documentId","events"])||result.configured!==true||result.documentId!==id||!Array.isArray(result.events)||result.events.length>50)throw new Error();const items=[];for(const entry of result.events){const event=checkedEvent(entry),item=document.createElement("li");item.textContent=dateLabel(event.at)+" ／ URLへのアクセス ／ "+sourceLabel(event.source)+" ／ "+(event.notifications.map(n=>n.state==="accepted"?"通知の送信受付済み":n.state==="failed"?"通知に失敗":"通知を送信待ち").join("・")||"通知なし")+" ／ イベントID: "+event.id;items.push(item);}el["canary-events"].replaceChildren(...items);el["canary-status"].textContent=items.length?"Canaryの記録を表示しました。":"Canaryの記録はありません。";}catch{if(active(g)){el["canary-events"].replaceChildren();el["canary-status"].textContent="Canaryの記録を読み込めませんでした。";}}finally{if(active(g)){busy=false;render();}}});
el["canary-panel"].addEventListener("toggle",()=>{if(el["canary-panel"].open&&!data)void read();});
async function boot(){const g=epoch;try{const value=await api("/v1/management");if(!active(g))return;if(!UUID.test(value?.documentId||""))throw new Error();id=value.documentId;if(el["canary-panel"].open)void read();}catch{if(active(g))el["canary-status"].textContent="Canaryの設定を読み込めませんでした。";}render();}
addEventListener("pagehide",()=>{visible=false;epoch++;busy=false;clearTimeout(expiryTimer);for(const c of controllers)c.abort();controllers.clear();id=null;data=null;uncertain=true;el["canary-url"].value="";el["canary-events"].replaceChildren();render();});addEventListener("pageshow",event=>{if(event.persisted){visible=true;void boot();}});
render();void boot();
`;
